{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8snet.serviceAccountName" . }}
  labels:
    {{- include "k8snet.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "k8snet.fullname" . }}
  labels:
    {{- include "k8snet.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "svc"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8snet.fullname" . }}
  labels:
    {{- include "k8snet.labels" . | nindent 4 }}
  name: {{ include "k8snet.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8snet.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8snet.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}